### ISSUE TITLE
Add possibility to choose a different langage for card

### ISSUE THREAD

**Issue by Slaschounet** [traiti/DEACT#1]
Hi,

First, thank you for your work.
I think it's a good idea to add different langage for cards in addition to different art, like Scryfall do.

What do you think ?

Best regards
Ps: i added you on steam

**Comment by antraiti** [comment]
Hi there,

Glad you are enjoying the application. I currently haven't been planning on any other additions but this sounds like a good improvement. It shouldn't be too much trouble so I will look into adding it when I get the spare time.

**Comment by antraiti** [comment]
Hello again, I just published a change that adds a dropdown to allow for language selection when choosing your card art. Hope this fulfills what you were needing. Please let me know if you run into any issues or something doesnt work. Thanks and glad you are enjoying the application!
